### ISSUE TITLE
Gra dowolna didn't unlock

### ISSUE THREAD

**Issue by Wolf480pl** [Ciunkos/koronakrulow#1]
I finished the basic gamemode (got "Epidemia opanowana") but the custom game mode didn't unlock.

**Comment by Ciunkos** [comment]
I will investigate that. For now, please reload the page and it should work. Thanks for the report!

**Comment by Ciunkos** [comment]
The problem should be fixed with https://github.com/Ciunkos/koronakrulow/commit/75b0c90c521dd77596b44c4b881121f0f744ac00. I will close the issue, if there are still any issues with the custom mode not being unlocked, please let me know.
